import "./layout.css";
import "./normalize.css"
import Header from '@/src/components/Header'

export const metadata = {
  title: "BLife | Home",
  description: "Generated by Moises Roberto",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="main">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
