export const metadata = {
  title: "BLife | Promoiciones",
  description: "Generated by Moises Roberto",
};

export default function PromocionesLayout({ children }) {
  return (
    <>
      {
        children
      }
    </>
  )
}
